Smoke test updates after 63
mantidproject/documents pull request #104
Opened 2022-02-14 17:47 UTC by DanielMurphy22

2022-02-15 16:02 UTC, martyngigg requested changes
Thanks for the updates.

I think `.idea/workspace.xml` might have snuck in from PyCharm?

2022-02-15 16:07 UTC, DanielMurphy22 commented
> Thanks for the updates.
> 
> I think `.idea/workspace.xml` might have snuck in from PyCharm?

Yes! I had noticed and was just messaging Conor about this! I want to dry run this on my personal repo first, but it'd be really good if you have a scan over the create_smoke_issues_OS.py script at some stage!

2022-02-18 11:19 UTC, DanielMurphy22 commented
I think the script create_smoke_issues_OS.py works now, but I still hit the secondary rate limits despite having the second waits: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits

2022-02-21 10:28 UTC, martyngigg requested changes
I really like to new smoke testing script. Just one question about it.

2022-02-21 10:28 UTC, martyngigg commented on Project-Management/Tools/RoadmapUpdate/SmokeTesting/create_smoke_issues_OS.py
> +def main() -> int:
Nice to see some type information!

2022-03-03 16:51 UTC, martyngigg approved these changes

2022-03-03 16:51 UTC, merged